import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || "",
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

// API Routes
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", service: "Precision-BRCA AI Server", timestamp: new Date().toISOString() });
});

// Precision Oncology AI Interpretation Endpoint
app.post("/api/patient/interpret", async (req, res) => {
  try {
    const { patientData } = req.body;

    if (!patientData) {
      return res.status(400).json({ error: "Missing patientData payload" });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.status(500).json({
        error: "GEMINI_API_KEY environment variable is missing. Please configure it in Settings > Secrets.",
      });
    }

    const prompt = `
You are an expert computational precision oncologist and genomic pathologist reviewing a patient profile generated by the Precision-BRCA AI multi-omics machine-learning framework.

PATIENT PROFILE DATA:
- Patient ID / Name: ${patientData.patientId || "BRCA-2026-PT"}
- Age: ${patientData.age}
- Menopausal Status: ${patientData.menopausalStatus}
- Clinical Stage: ${patientData.tumorStage} (T: ${patientData.tumorSize}cm, Nodes: ${patientData.nodeStatus})
- Receptor Status (IHC): ER: ${patientData.erStatus}, PR: ${patientData.prStatus}, HER2: ${patientData.her2Status}
- Calculated Cancer Probability: ${patientData.cancerProbability}% (Illustrative Computational Output — Not Clinically Validated)
- Predicted Molecular Subtype: ${patientData.molecularSubtype} (Confidence: ${patientData.subtypeConfidence}%)
- Prognostic Risk Score: ${patientData.prognosticRisk} (5-Year Predicted Overall Survival Risk: ${patientData.fiveYearRisk}% - Illustrative Computational Output — Not Clinically Validated)

KEY GENE EXPRESSION & SHAP BIOMARKERS:
${JSON.stringify(patientData.topGenes || [], null, 2)}

MAJOR DYSREGULATED PATHWAYS:
${(patientData.pathways || []).join(", ")}

PRIORITIZED THERAPEUTIC TARGETS & CANDIDATE DRUGS:
${JSON.stringify(patientData.targets || [], null, 2)}

CRITICAL SCIENTIFIC RIGOR & LABELLING MANDATES:
1. Numerical Predictions: Whenever citing Cancer Probability (e.g. ${patientData.cancerProbability}%) or 5-Year OS Risk (e.g. ${patientData.fiveYearRisk}%), append "(Illustrative Computational Output — Not Clinically Validated)".
2. BRCA1 Scientific Precision: Do NOT state that BRCA1 alteration "leads to Homologous Recombination Deficiency (HRD)". Instead state: "BRCA1 alteration and reduced expression are consistent with impaired homologous-recombination repair; functional HRD status requires independent genomic/functional assessment."
3. TP53 Scientific Precision: Do NOT claim that TP53 mutation signifies a "dominant-negative or gain-of-function mutant protein" without variant-level/functional evidence. Instead state: "TP53 mutation with elevated transcript expression is consistent with TP53 dysregulation; specific dominant-negative or gain-of-function effects require variant-level functional evidence."
4. Heading Exactness: Section 4 must be titled exactly "### 4. Potentially Relevant Clinical Trial Opportunities" (never duplicate the word "Potentially").

Please provide a structured, highly authoritative, computational oncology research report with the following sections formatted in clear Markdown:

CRITICAL CITATION REQUIREMENT:
Every externally sourced clinical, biological, or translational claim throughout Sections 1–4 MUST include explicit in-text citation/reference numbers directly in the text (e.g., [1], [2], [1, 3]). For instance, any statement regarding ctDNA surveillance (such as rising mutant allele fraction [MAF] preceding radiologic progression by 4–6 months), prospective clinical trial endpoints, FDA companion diagnostics, or PAM50/TCGA classification must be cited with a bracketed reference number that corresponds directly to Section 5.

### 1. Computational & Molecular Analysis
Start with: "The computational ensemble identifies the sample as consistent with a ${patientData.molecularSubtype} (${patientData.molecularSubtype === 'Basal-like' ? 'triple-negative breast cancer' : patientData.molecularSubtype + ' breast cancer'}) molecular profile. These results represent computational predictions derived from the available molecular and clinical inputs and should not be interpreted as independently validated clinical diagnoses."
Then present the COMPUTATIONAL ONCOLOGY PROFILE in the following Markdown table format:
| Parameter / Metric | Computational Assessment / Clinical Value |
|---|---|
| Patient ID | ${patientData.patientId || 'TCGA-BRCA-A2-010'} |
| Age / Menopause | ${patientData.age} years / ${patientData.menopauseStatus} |
| Clinical Stage | ${patientData.tumorStage} (T: ${patientData.tumorSize} cm, N1: ${patientData.nodeStatus}) |
| IHC Receptor Status | ER-${patientData.erStatus}, PR-${patientData.prStatus}, HER2-${patientData.her2Status} (${patientData.molecularSubtype === 'Basal-like' ? 'TNBC' : patientData.molecularSubtype}) |
| Predicted Subtype | ${patientData.molecularSubtype} (PAM50 Probability: ${patientData.subtypeConfidence}%) [11, 14, 15] |
| Cancer Probability | ${patientData.cancerProbability}% (Illustrative Computational Output — Not Clinically Validated) [14] |
| Prognostic OS Risk | ${patientData.prognosticRisk} Risk (5-Year Predicted Overall Survival Risk: ${patientData.fiveYearRisk}% - Illustrative Computational Output — Not Clinically Validated) [11, 15] |

Provide concise computational interpretation of why the ensemble classified this patient as ${patientData.molecularSubtype} with ${patientData.prognosticRisk} risk. Include in-text citations [N].

### 2. SHAP Biomarker Mechanistic Rationale
Include this exact interpretation notice first:
"Interpretation: SHAP values describe the contribution of individual input features to the model output. They represent model behavior and do not independently establish biological causality or clinical significance."

Present the SHAP FEATURE ATTRIBUTION VECTOR (MODEL RISK CONTRIBUTION) in the following Markdown table format:
| Feature / Biomarker | SHAP Value (Weight) | Direction / Vector | Mechanistic Attribution |
|---|---|---|---|
| BRCA1 [Mutated / Low] | +0.28 | Positive Risk (=>) | Pivotal Driver |
| TP53 [Mutated / High] | +0.24 | Positive Risk (=>) | Pivotal Driver |
| EGFR [Overexpressed] | +0.19 | Positive Risk (=>) | RTK Driver |
| MKI67 [Overexpressed] | +0.16 | Positive Risk (=>) | Proliferation |
| PARP1 [Overexpressed] | +0.12 | Positive Risk (=>) | BER Compensatory |
| ESR1 [Underexpressed] | -0.15 | Negative Risk (<=) | Subtype Vector |

Then explain the biological mechanism of the top SHAP contributing biomarkers, highlighting driver vs passenger alterations and why specific genes (like ${patientData.topGenes?.[0]?.gene || 'key drivers'}) drive high or low prognostic risk. Include in-text citations [N].

### 3. Therapeutic Evidence & Candidate Vulnerabilities
Present the candidate therapeutic evidence in the following table format:
| Target / Vulnerability | Candidate Drug(s) | Evidence / Development Status | DepMap CERES Score (24Q2) | GDSC IC50 Score | ESCAT / Evidence Level |
|---|---|---|---|---|---|
| BRCA1/2-associated HRR deficiency | Olaparib / Talazoparib | FDA-approved in specific BRCA breast cancer | -1.12 (Dependency) | -2.45 (Sensitive) | Tier I-A [1,7,10] |
| EGFR | Cetuximab | Investigational / clinical-trial | -0.78 (Dependency) | -1.85 (Sensitive) | Tier II-B [4,8] |
| ATR | Ceralasertib (AZD6738) | Investigational / Phase II | -0.89 (Dependency) | -1.95 (Sensitive) | Tier II-A [8,9] |

Immediately below the table, include this exact interpretation paragraph:
"Interpretation: DepMap CERES and GDSC values represent population-level preclinical dependency and drug-sensitivity signals and should not be interpreted as patient-specific treatment-response predictions. Therapeutic relevance requires independent assessment of molecular eligibility, disease setting, prior treatment history, current guidelines, and clinical-trial criteria."

### 4. Potentially Relevant Clinical Trial Opportunities
Include this exact guidance notice first:
"Trial relevance should be independently assessed using current eligibility criteria, biomarker requirements, disease stage, prior treatment history, geographic availability, and investigator review."

Present the SERIAL ctDNA SURVEILLANCE & RADIOLOGIC LEAD TIME TIMELINE in the following Markdown table format:
| Surveillance Milestone | Clinical & Molecular Monitoring Event | Evidence Benchmark / Reference |
|---|---|---|
| Month 0 (Baseline) | Surgery / Neoadjuvant Resection Complete | Baseline Pathologic Stage [11] |
| Month 3 (Adjuvant) | Adjuvant Chemotherapy Initiation & ctDNA Nadir | Standard Systemic Regimen [11] |
| Month 6 (ctDNA+) | Rising ctDNA MAF Detected (Molecular Recurrence) | 4–6 Month Subclinical Lead Time [1, 2, 13, 14] |
| Month 10–12 (Progression) | Radiologic Recurrence Verified by RECIST 1.1 Criteria | Overt Metastatic Relapse [1, 2, 11] |

Immediately below the timeline table, include this exact interpretation note:
"Interpretation: Serial liquid biopsy ctDNA surveillance detects occult recurrence with a 4–6 month median lead time prior to conventional radiologic detection by CT/PET-CT, enabling potential molecular-directed clinical trial intervention before symptomatic disease progression."

Then discuss potentially relevant clinical trial opportunities (e.g. prospective biomarker-directed trials) and investigational biomarker monitoring panels. Include in-text citations [N].

### 5. References & Evidence Sources
Provide direct, numbered references corresponding to each in-text citation, organized under the following 8 exact categories:

#### PubMed
- Numbered citations with PMID, authors, article title, journal, year, and key clinical finding (including the ctDNA lead time finding: e.g. Garcia-Murillas et al., Sci Transl Med 2015 PMID: 26311728 / Coombes et al., Clin Cancer Res 2019 PMID: 31097499; Robson et al. NEJM PMID: 28575631; André et al. NEJM PMID: 31091374).

#### ClinicalTrials.gov
- Numbered clinical trial entries with prospective NCT identifiers (e.g., NCT02000622 OlympiAD, NCT03056833 SOLAR-1, NCT02422615 monarchE).

#### FDA
- Numbered regulatory approvals, NDA numbers, and companion diagnostic (CDx) clearances (e.g., Lynparza/BRACAnalysis CDx, Piqray/therascreen PIK3CA RGQ PCR, Verzenio).

#### NCCN / ASCO / ESMO (where applicable)
- Numbered clinical guideline recommendations and ESCAT actionability tiers (e.g., NCCN Breast Cancer v2.2024 Category 1, ESCAT Tier I-A/I-B).

#### DepMap
- Numbered Broad Institute Cancer Dependency Map (DepMap 24Q2) CRISPR-Cas9 CERES gene effect scores and lineage dependency validations.

#### GDSC
- Numbered Wellcome Sanger Institute Genomics of Drug Sensitivity in Cancer (GDSC2) pharmacological screening and IC50 response profiles.

#### TCGA / GDC
- Numbered NCI Genomic Data Commons TCGA-BRCA primary baseline cohort metrics (n=1,098 primary tumor cases).

#### GEO
- Numbered NCBI Gene Expression Omnibus external validation series (e.g., GSE96058 SCAN-B cohort n=3,273, GSE20685, GSE21653).

### MODEL & DATA PROVENANCE
- Data source: TCGA-BRCA research dataset
- Analysis type: Computational / AI-assisted
- Molecular inputs: Expression, mutation and clinical features
- Explainability: SHAP
- Evidence sources: PubMed, ClinicalTrials.gov, FDA, NCCN/ASCO/ESMO, DepMap, GDSC, TCGA/GDC and GEO
- Validation status: Research prototype — not clinically validated
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are Precision-BRCA AI, a computational oncology research intelligence engine. Note: All analyses are for AI-Assisted Computational Analysis — Research Use Only (RUO) and not for clinical diagnostic or treatment decision-making. You must cite every specific clinical statement (such as trial hazard ratios, drug indications, or ctDNA rising MAF preceding radiologic progression by 4-6 months) with a bracketed reference number [N] that maps directly to the numbered References & Evidence Sources section covering PubMed, ClinicalTrials.gov, FDA, NCCN/ASCO/ESMO, DepMap, GDSC, TCGA/GDC, and GEO.",
        temperature: 0.2,
      },
    });

    const reportText = response.text || "Unable to generate oncology interpretation report.";

    res.json({
      success: true,
      report: reportText,
      timestamp: new Date().toISOString(),
    });
  } catch (error: any) {
    console.error("Error generating oncology interpretation:", error);
    res.status(500).json({
      error: error.message || "Failed to generate precision oncology AI report.",
    });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Precision-BRCA AI Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
